# Generated by Django 5.1.4 on 2025-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
