# Generated by Django 5.1.4 on 2025-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzle', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='category_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=40),
        ),
    ]
