# Generated by Django 5.1.4 on 2025-01-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizzle', '0004_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
